worker_upstream {
    server ai_backend:8000;
    server ecm_backend:8000;
    server erp_backend:8000;
    server vpn_backend:8000;
    server mkt_backend:8000;
}

events { }

http {
    upstream frontends {
        server ai_frontend:3000;
        server ecm_frontend:3000;
        server erp_frontend:3000;
        server vpn_frontend:3000;
        server mkt_frontend:3000;
    }

    server {
        listen 80;

        location /ai/   { proxy_pass http://ai_backend:8000; }
        location /ecm/  { proxy_pass http://ecm_backend:8000; }
        location /erp/  { proxy_pass http://erp_backend:8000; }
        location /vpn/  { proxy_pass http://vpn_backend:8000; }
        location /mkt/  { proxy_pass http://mkt_backend:8000; }
    }
}
